import { Product } from "@/types";

export const products: Product[] = [
  {
    id: '1',
    name: 'TORTA SELVA NEGRA',
    description: 'Cheesecake de maracuya',
    price: 35.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Postres',
    stock: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'TORTA TRES LECHES VAINILLA',
    description: 'Brazo gitano',
    price: 40.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Postres',
    stock: 15,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'TORTA MOKA',
    description: 'Torta amor meme - butter cream',
    price: 90.00,
    originalPrice: 140.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'TORTA SUBLIME',
    description: 'Torta para hombre con degradado - butter cream',
    price: 90.00,
    originalPrice: 150.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
   {
    id: '5',
    name: 'TORTA CROCANTE DE CHOCOLATE',
    description: 'Torta para hombre con degradado - butter cream',
    price: 90.00,
    originalPrice: 150.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'TRES LECHES DOBLE CHOCOLATE',
    description: 'Torta para hombre con degradado - butter cream',
    price: 90.00,
    originalPrice: 150.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    id: '7',
    name: 'TRES LECHES DOBLE COCO',
    description: 'Torta para hombre con degradado - butter cream',
    price: 90.00,
    originalPrice: 150.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
   {
    id: '8',
    name: 'TRES LECHES DE OREO',
    description: 'Torta para hombre con degradado - butter cream',
    price: 35.00,
    originalPrice: 150.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];