import { Product } from "@/types";

export const productsThemed: Product[] = [
  {
    id: '1',
    name: 'TORTA LOVE - BUTTER CREAM',
    description: 'Cheesecake de maracuya',
    price: 35.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Postres',
    stock: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'TORTA AMOR MEME - BUTTER CREAM',
    description: 'Brazo gitano',
    price: 40.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Postres',
    stock: 15,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'TORTA PARA HOMBRE CON DEGRADADO - BUTTER CREAM',
    description: 'Torta amor meme - butter cream',
    price: 90.00,
    originalPrice: 140.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'TORTA PARA MUJER CON FLORES Y TOOPER - BUTTER CREAM',
    description: 'Torta para hombre con degradado - butter cream',
    price: 90.00,
    originalPrice: 150.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
   {
    id: '5',
    name: 'TORTA PARA NIÑA DE COLA DE SIRENITAS - BUTTER CREAM',
    description: 'Torta para hombre con degradado - butter cream',
    price: 90.00,
    originalPrice: 150.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'TORTA PARA NIÑO DE SONIC -BUTTER CREAM',
    description: 'Torta para hombre con degradado - butter cream',
    price: 90.00,
    originalPrice: 150.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    {
    id: '7',
    name: 'TORTA LOVE - CHANTILLY',
    description: 'Torta para hombre con degradado - butter cream',
    price: 90.00,
    originalPrice: 150.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
   {
    id: '8',
    name: 'TORTA AMOR MEME - CHANTILLY',
    description: 'Torta para hombre con degradado - butter cream',
    price: 35.00,
    originalPrice: 150.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];