import { Product } from '@/types';

// Fecha estática para evitar errores de hidratación
const STATIC_DATE = new Date('2024-01-01T00:00:00.000Z');

// Productos para tortas en línea
export const tortasProducts: Product[] = [
  {
    id: '1',
    name: 'TORTA SELVA NEGRA',
    description: 'Torta clásica con chocolate y crema chantilly',
    price: 35.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 10,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '2',
    name: 'TORTA TRES LECHES VAINILLA',
    description: 'Torta tres leches con sabor a vainilla',
    price: 40.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 15,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '3',
    name: 'TORTA MOKA',
    description: 'Torta con café y chocolate',
    price: 45.00,
    originalPrice: 55.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 5,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '4',
    name: 'TORTA SUBLIME',
    description: 'Torta con chocolate y manjar',
    price: 42.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 8,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '5',
    name: 'TORTA CROCANTE DE CHOCOLATE',
    description: 'Torta con chocolate y crocante',
    price: 48.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 12,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '6',
    name: 'TRES LECHES DOBLE CHOCOLATE',
    description: 'Tres leches con chocolate negro y blanco',
    price: 38.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 7,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '7',
    name: 'TRES LECHES DOBLE COCO',
    description: 'Tres leches con coco rallado',
    price: 36.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 9,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '8',
    name: 'TRES LECHES DE OREO',
    description: 'Tres leches con galletas Oreo',
    price: 35.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas',
    stock: 11,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
];

// Productos para tortas temáticas
export const tortasTematicasProducts: Product[] = [
  {
    id: '9',
    name: 'TORTA LOVE - BUTTER CREAM',
    description: 'Torta temática de amor con butter cream',
    price: 35.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas Temáticas',
    stock: 10,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '10',
    name: 'TORTA AMOR MEME - BUTTER CREAM',
    description: 'Torta temática meme con butter cream',
    price: 40.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas Temáticas',
    stock: 15,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '11',
    name: 'TORTA PARA HOMBRE CON DEGRADADO - BUTTER CREAM',
    description: 'Torta para hombre con degradado de colores',
    price: 90.00,
    originalPrice: 140.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas Temáticas',
    stock: 5,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '12',
    name: 'TORTA PARA MUJER CON FLORES Y TOOPER - BUTTER CREAM',
    description: 'Torta para mujer con flores y topper personalizado',
    price: 90.00,
    originalPrice: 150.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas Temáticas',
    stock: 8,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '13',
    name: 'TORTA PARA NIÑA DE COLA DE SIRENITAS - BUTTER CREAM',
    description: 'Torta temática de La Sirenita para niñas',
    price: 85.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas Temáticas',
    stock: 6,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '14',
    name: 'TORTA PARA NIÑO DE SONIC - BUTTER CREAM',
    description: 'Torta temática de Sonic para niños',
    price: 85.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas Temáticas',
    stock: 4,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '15',
    name: 'TORTA LOVE - CHANTILLY',
    description: 'Torta temática de amor con chantilly',
    price: 80.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas Temáticas',
    stock: 7,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '16',
    name: 'TORTA AMOR MEME - CHANTILLY',
    description: 'Torta temática meme con chantilly',
    price: 35.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Tortas Temáticas',
    stock: 9,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
];

// Productos para postres
export const postresProducts: Product[] = [
  {
    id: '17',
    name: 'CHEESECAKE DE MARACUYA',
    description: 'Cheesecake con sabor a maracuyá',
    price: 25.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Postres',
    stock: 12,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '18',
    name: 'BRAZO GITANO',
    description: 'Brazo gitano tradicional',
    price: 20.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Postres',
    stock: 15,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '19',
    name: 'TIRAMISÚ',
    description: 'Tiramisú italiano con café',
    price: 28.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Postres',
    stock: 8,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '20',
    name: 'FLAN DE CARAMELO',
    description: 'Flan casero con caramelo',
    price: 18.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Postres',
    stock: 20,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '21',
    name: 'MOUSSE DE CHOCOLATE',
    description: 'Mousse de chocolate negro',
    price: 22.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Postres',
    stock: 10,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: '22',
    name: 'PASTEL DE TRES LECHES',
    description: 'Pastel individual de tres leches',
    price: 15.00,
    image: '/imgs/banners/banner2.jpg',
    category: 'Postres',
    stock: 25,
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
];
